# Generated by Django 4.1.3 on 2022-11-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Teachers',
        ),
    ]
