name: Test coverage CI

on:
  push:
    branches-ignore: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install django-nose
    - name: Test Coverage
      run: |
        cd ../..
        cd EasyFooder/src/Django/EasyFooder
        coverage run manage.py test
        coverage report -m
    - name: Run Tests
      run: |
        python manage.py test
        
